accepted = [
    "0BSD",
    "Apache-2.0",
    "MIT",
    "Unicode-3.0",
    "Unlicense",
    "Zlib",
]
targets = ["aarch64-apple-darwin"]
ignore-build-dependencies = false
ignore-dev-dependencies = true
ignore-transitive-dependencies = false
